### PR TITLE
Deprecate tracing API

### LINKED ISSUE #260: Deprecate the tracing API
The tracing API is attached in wrong place so it has to be changed. We should deprecate the current API as it is planned to be changed.

### PR DESCRIPTION
**Pull request by chfast**
Closes #260.

### CODE REVIEW

File: include/evmc/evmc.h [hunk 1]
```diff
@@ -991,7 +991,12 @@ struct evmc_instance
      * Optional pointer to function setting the EVM instruction tracer.
      *
      * If the EVM does not support this feature the pointer can be NULL.
+     *
+     * @deprecated
+     * The tracing API from EVMC 6 has been deprecated as there have been some
+     * design flaws discovered. New API is expected to be introduced in future.
      */
+    EVMC_DEPRECATED
```
Comment (chfast) [inline include/evmc/evmc.h]: We cannot put [[deprecated]] attribute here because it makes the `evmc_instance` non-constuctable in some compilers: https://circleci.com/gh/ethereum/evmc/13261.

File: include/evmc/evmc.h [hunk 2]
```diff
@@ -991,6 +991,10 @@ struct evmc_instance
      * Optional pointer to function setting the EVM instruction tracer.
      *
      * If the EVM does not support this feature the pointer can be NULL.
+     *
+     * @deprecated
+     * The tracing API from EVMC 6 has been deprecated as there have been some
```
Comment (gumb0) [inline include/evmc/evmc.h]: It's not deprecated in 6.2, should this say `from EVMC 6.3` ?

**Comment by gumb0** [comment]
What about `evmc_set_tracer_fn`, `evmc_trace_callback`, `evmc_tracer_context`, they stay?

**Comment by chfast** [comment]
> What about `evmc_set_tracer_fn`, `evmc_trace_callback`, `evmc_tracer_context`, they stay?

We can only use `@deprecated` in doxygen there, because otherwise we will generate warnings in other places.
