### PR TITLE
ci: Test C++17 mode in MSVC

### LINKED ISSUE #261: CI: Build in C++17 mode
Not confirmed yet, but looks like MSVC in C++17 fails to build EVMC vmtester: https://ci.appveyor.com/project/chfast/evmone/builds/24281811.

### PR DESCRIPTION
**Pull request by chfast**
Fixes #261 

This is GTest issue: https://github.com/google/googletest/issues/1616

### CODE REVIEW

File: test/unittests/test_instructions.cpp [hunk 1]
```diff
@@ -15,7 +15,7 @@ TEST(instructions, homestead_hard_fork)
 
     EXPECT_EQ(f[OP_DELEGATECALL].gas_cost, -1);
     EXPECT_EQ(h[OP_DELEGATECALL].gas_cost, 40);
-    EXPECT_EQ(fn[OP_DELEGATECALL], nullptr);
+    EXPECT_TRUE(fn[OP_DELEGATECALL] == nullptr);
```
Comment (axic) [inline test/unittests/test_instructions.cpp]: Why are these needed?

Comment (chfast) [reply test/unittests/test_instructions.cpp]: Printing of `nullptr` does not compile in MSVC because of the GTest issue.
